name: kinclongin
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  intl: ^0.20.2
  http: ^1.4.0
  logger: ^2.5.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.9
  permission_handler: ^11.3.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  provider: ^6.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.7.7
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

